Background@SETTINGS_MENU:
	Id:SETTINGS_MENU
	Logic:SettingsMenuLogic
	X:(WINDOW_RIGHT - WIDTH)/2
	Y:(WINDOW_BOTTOM- HEIGHT)/2
	Width: 450
	Height: 350
	Children:
		Label@SETTINGS_LABEL_TITLE:
			Id:SETTINGS_LABEL_TITLE
			X:0
			Y:20
			Width:450
			Height:25
			Text:Settings
			Align:Center
			Font:Bold
		Button@BUTTON_CLOSE:
			Id:BUTTON_CLOSE
			X:PARENT_RIGHT - 180
			Y:PARENT_BOTTOM - 45
			Width:160
			Height:25
			Text:Close
			Font:Bold
			Key:escape
		Container@TAB_CONTAINER:
			Id:TAB_CONTAINER
			X:0
			Y:50
			Width:PARENT_RIGHT
			Height:25
			Children:
				Button@GENERAL:
					Id:GENERAL
					X:45
					Y:0
					Width:90
					Height:25
					Text:General
					Font:Bold
				Button@AUDIO:
					Id:AUDIO
					X:135
					Y:0
					Width:90
					Height:25
					Text:Audio
					Font:Bold
				Button@DISPLAY:
					Id:DISPLAY
					X:225
					Y:0
					Width:90
					Height:25
					Text:Display
					Font:Bold
				Button@DEBUG:
					Id:DEBUG
					X:315
					Y:0
					Width:90
					Height:25
					Text:Debug
					Font:Bold
		Container@GENERAL_PANE:
			Id:GENERAL_PANE
			X:37
			Y:100
			Width:PARENT_RIGHT - 37
			Height:PARENT_BOTTOM - 100
			Visible: true
			Children:
				Label@SETTINGS_PLAYER_NAME:
					Id:SETTINGS_PLAYER_NAME
					X:0
					Y:10
					Text: Player Name:
				TextField@NAME:
					Id:NAME
					Text:Name
					Width:139
					Height:25
					X:90
					Y:0
					MaxLength:16
				Checkbox@EDGE_SCROLL:
					Id:EDGE_SCROLL
					X:0
					Y:30
					Width:200
					Height:20
					Text: Enable Edge Scrolling
				Label@EDGE_SCROLL_AMOUNT_LABEL:
					Id:EDGE_SCROLL_AMOUNT_LABEL
					X:0
					Y:70
					Text: Scroll Speed
				Slider@EDGE_SCROLL_AMOUNT:
					Id:EDGE_SCROLL_AMOUNT
					X:130
					Y:60
					Width:250
					Height:20
					Ticks:5
					MinimumValue: 10
					MaximumValue: 50
				Checkbox@INVERSE_SCROLL:
					Id:INVERSE_SCROLL
					X:0
					Y:90
					Width:200
					Height:20
					Text: Invert Mouse Drag Scrolling
				Checkbox@TEAMCHAT_TOGGLE:
					Id:TEAMCHAT_TOGGLE
					X:0
					Y:120
					Width:200
					Height:20
					Text: Shift-Enter Toggles Team Chat
				Checkbox@SHOW_SHELLMAP:
					Id:SHOW_SHELLMAP
					X:0
					Y:150
					Width:200
					Height:20
					Text: Show Shellmap
		Container@AUDIO_PANE:
			Id:AUDIO_PANE
			X:37
			Y:100
			Width:PARENT_RIGHT - 37
			Height:PARENT_BOTTOM - 100
			Visible: false
			Children:
				Label@SOUND_VOLUME_LABEL:
					Id:SOUND_VOLUME_LABEL
					X:0
					Y:10
					Text: Sound Volume		
				Slider@SOUND_VOLUME:
					Id:SOUND_VOLUME
					X:100
					Y:0
					Width:250
					Height:20
					Ticks:5
				Label@MUSIC_VOLUME_LABEL:
					Id:MUSIC_VOLUME_LABEL
					X:0
					Y:40
					Text: Music Volume
				Slider@MUSIC_VOLUME:
					Id:MUSIC_VOLUME
					X:100
					Y:30
					Width:250
					Height:20
					Ticks:5
		Container@DISPLAY_PANE:
			Id:DISPLAY_PANE
			X:37
			Y:100
			Width:PARENT_RIGHT - 37
			Height:PARENT_BOTTOM - 100
			Visible: false
			Children:
				Label@MODE_LABEL:
					X:0
					Y:0
					Width:45
					Height:25
					Text:Mode:
				DropDownButton@MODE_DROPDOWN:
					Id:MODE_DROPDOWN
					X:50
					Y:1
					Width:170
					Height:25
					Font:Regular
					Text:Windowed
				Container@WINDOWRES:
					Id:WINDOW_RESOLUTION
					X:220
					Y:0
					Children:
						Label@At:
							Text:@
							Font:Bold
							Y:0-1
							Height:25
							Width:25
							Align:Center
						TextField@SCREEN_WIDTH:
							Id:WINDOW_WIDTH
							X:25
							Width:45
							Height:25
							MaxLength:5
						Label@X:
							Text:x
							Font:Bold
							X:70
							Y:0-1
							Height:25
							Width:15
							Align:Center
						TextField@SCREEN_HEIGHT:
							Id:WINDOW_HEIGHT
							X:85
							Width:45
							Height:25
							MaxLength:5
				Label@VIDEO_DESC:
					Y:25
					Width:PARENT_RIGHT
					Height:25
					Font:Tiny
					Align:Center
					Text:Mode/Resolution changes will be applied after the game is restarted
				Checkbox@PIXELDOUBLE_CHECKBOX:
					Id:PIXELDOUBLE_CHECKBOX
					Y:50
					Width:200
					Height:20
					Font:Regular
					Text:Enable Pixel Doubling
		Container@DEBUG_PANE:
			Id:DEBUG_PANE
			X:37
			Y:100
			Width:PARENT_RIGHT - 37
			Height:PARENT_BOTTOM - 100
			Visible: false
			Children:
				Checkbox@PERFDEBUG_CHECKBOX:
					Id:PERFDEBUG_CHECKBOX
					X:0
					Y:0
					Width:300
					Height:20
					Text:Show Performance Information
				Checkbox@CHECKUNSYNCED_CHECKBOX:
					Id:CHECKUNSYNCED_CHECKBOX
					X:0
					Y:30
					Width:300
					Height:20
					Text:Check Sync around Unsynced Code
