Container@SETTINGS_PANEL:
	Logic:CncSettingsLogic
	X:(WINDOW_RIGHT - WIDTH)/2
	Y:(WINDOW_BOTTOM - 250)/2
	Width:740
	Height:535
	Children:
		ColorPreviewManager@COLOR_MANAGER:
		Label@TITLE:
			Width:740
			Y:0-25
			Font:BigBold
			Contrast:true
			Align:Center
			Text:Settings
		Background@GENERAL_CONTROLS:
			Width:740
			Height:290
			Background:panel-black
			Children:
				Label@TITLE:
					X:15
					Y:20
					Font:Bold
					Text:Player Profile
					Align:Center
					Width:340
				Label@NAME_LABEL:
					X:15
					Y:39
					Width:45
					Height:25
					Align:Right
					Text:Name:
				TextField@NAME_TEXTFIELD:
					X:65
					Y:40
					Width:205
					Height:25
					MaxLength:16
				DropDownButton@COLOR:
					X:275
					Y:40
					Width:80
					Height:25
					IgnoreChildMouseOver: true
					Children:
						ColorBlock@COLORBLOCK:
							X:5
							Y:6
							Width:PARENT_RIGHT-35
							Height:PARENT_BOTTOM-12
				Label@DEBUG_TITLE:
					X:15
					Y:100
					Width:340
					Font:Bold
					Text:Debug
					Align:Center
				Checkbox@PERFTEXT_CHECKBOX:
					X:15
					Y:120
					Width:300
					Height:20
					Font:Regular
					Text:Show Performance Text
				Checkbox@PERFGRAPH_CHECKBOX:
					X:15
					Y:150
					Width:300
					Height:20
					Font:Regular
					Text:Show Performance Graph
				Checkbox@CHECKUNSYNCED_CHECKBOX:
					X:15
					Y:180
					Width:300
					Height:20
					Font:Regular
					Text:Check Sync around Unsynced Code
				Checkbox@SHELLMAP_MUSIC:
					X:15
					Y:210
					Width:200
					Height:20
					Font:Regular
					Text:Shellmap Music
				Label@VIDEO_TITLE:
					Y:20
					X:375
					Font:Bold
					Text:Graphics
					Align:Center
					Width:340
				Label@MODE_LABEL:
					X:375
					Y:39
					Width:45
					Height:25
					Align:Right
					Text:Mode:
				DropDownButton@MODE_DROPDOWN:
					X:425
					Y:40
					Width:170
					Height:25
					Font:Regular
					Text:Windowed
				Container@WINDOW_RESOLUTION:
					X:595
					Y:40
					Children:
						Label@At:
							Text:@
							Font:Bold
							Y:0-1
							Height:25
							Width:25
							Align:Center
						TextField@WINDOW_WIDTH:
							X:25
							Width:45
							Height:25
							MaxLength:5
						Label@X:
							Text:x
							Font:Bold
							X:70
							Y:0-1
							Height:25
							Width:15
							Align:Center
						TextField@WINDOW_HEIGHT:
							X:85
							Width:45
							Height:25
							MaxLength:5
				Label@VIDEO_DESC:
					X:375
					Y:65
					Width:340
					Height:25
					Font:Tiny
					Align:Center
					Text:Mode/Resolution changes will be applied after the game is restarted
				Checkbox@PIXELDOUBLE_CHECKBOX:
					X:375
					Y:90
					Width:200
					Height:20
					Font:Regular
					Text:Enable Pixel Doubling
				Checkbox@SHOW_SHELLMAP:
					X:375
					Y:120
					Width:200
					Height:20
					Font:Regular
					Text:Show Shellmap
				Label@AUDIO_TITLE:
					X:375
					Y:160
					Width:340
					Font:Bold
					Text:Sound
					Align:Center
				Label@SOUND_LABEL:
					X:375
					Y:175
					Width:95
					Height:25
					Align:Right
					Text:Sound Volume:
				Slider@SOUND_SLIDER:
					X:475
					Y:180
					Width:240
					Height:20
					Ticks:5
				Label@MUSIC_LABEL:
					X:375
					Y:205
					Width:95
					Height:25
					Align:Right
					Text:Music Volume:
				Slider@MUSIC_SLIDER:
					X:475
					Y:210
					Width:240
					Height:20
					Ticks:5
				Label@AUDIO_DEVICE_LABEL:
					X:375
					Y:240
					Width:75
					Height:20
					Text:Audio Device:
				DropDownButton@AUDIO_DEVICE:
					X:475
					Y:240
					Width:240
					Height:25
					Font:Regular
					Text:Default Device
				Label@AUDIO_DESC:
					X:400
					Y:262
					Width:200
					Height:25
					Font:Tiny
					Text:Device changes will be applied after the game is restarted.
		Background@INPUT_CONTROLS:
			Width:740
			Height:290
			Background:panel-black
			Visible:false
			Children:
				Label@MOUSE_TITLE:
					Font:Bold
					Text:Mouse Input
					Align:Center
					X:15
					Y:20
					Width:340
				Checkbox@CLASSICORDERS_CHECKBOX:
					X:15
					Y:35
					Width:250
					Height:20
					Font:Regular
					Text:Left-Click Orders
				Label@SCROLL_TITLE:
					Font:Bold
					Text:Scroll Behavior
					Align:Center
					X:20
					Y:100
					Width:335
				Label@SCROLL_SPEED_LABEL:
					X:10
					Y:115
					Width:95
					Height:25
					Text:Scroll Speed:
				Slider@SCROLLSPEED_SLIDER:
					X:100
					Y:120
					Width:240
					Height:20
					Ticks:5
					MinimumValue: 10
					MaximumValue: 50
				Checkbox@EDGESCROLL_CHECKBOX:
					X:15
					Y:150
					Width:130
					Height:20
					Font:Regular
					Text:Edge Scrolling
				Label@MOUSE_SCROLL_LABEL:
					X:15
					Y:180
					Width:160
					Height:20
					Font:Regular
					Text:Middle-Mouse Scrolling:
					Align:Right
				DropDownButton@MOUSE_SCROLL:
					X:180
					Y:180
					Width:100
					Height:25
					Font:Regular
					Text:Enabled
				Label@KEYBOARD_TITLE:
					X:375
					Y:20
					Width:340
					Font:Bold
					Text:Keyboard Input
					Align:Center
				Checkbox@TEAMCHAT_CHECKBOX:
					X:375
					Y:35
					Width:240
					Height:20
					Font:Regular
					Text:Shift-Enter Toggles Team Chat
		Button@GENERAL_BUTTON:
			Y:289
			Width:140
			Height:35
			Text:General
		Button@INPUT_BUTTON:
			X:150
			Y:289
			Width:140
			Height:35
			Text:Input
		Button@BACK_BUTTON:
			Key:escape
			X:600
			Y:289
			Width:140
			Height:35
			Text:Back
